root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/server"
  pre_cmd = ["templ generate"]
  cmd = "go build -o ./tmp/server ./src/cmd/server"
  delay = 1000
  exclude_dir = ["tmp", "bin", "data", "src/static", "node_modules", "e2e"]
  exclude_regex = ["_test.go", "_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_ext = ["go", "templ"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[log]
  time = false

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[misc]
  clean_on_exit = true
